package encoders
import api.HelloResponseEncoders
import encoders.ToDoEncoders
import encoders.ToDoEncoders
import encoders.ToDoEncoders

trait ResponseEncoders extends ErrorResponseEncoders with HelloResponseEncoders with ToDoEncoders
